-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 05, 2023 at 05:20 PM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `wp_blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `name`, `slug`, `created_at`, `updated_at`) VALUES
(1, 'Musik', 'musik', '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(2, 'Personal', 'personal', '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(3, 'Liburan', 'liburan', '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(4, 'Kuliner', 'kuliner', '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(5, 'Hiburan', 'hiburan', '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(6, 'Teknologi', 'teknologi', '2023-09-04 22:56:05', '2023-09-04 22:56:05');

-- --------------------------------------------------------

--
-- Table structure for table `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2019_08_19_000000_create_failed_jobs_table', 1),
(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(5, '2023_09_02_050540_create_posts_table', 1),
(6, '2023_09_02_063216_create_categories_table', 1),
(7, '2023_09_05_101754_add_is_admin_to_users_table', 2);

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `personal_access_tokens`
--

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `category_id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `category_id`, `user_id`, `title`, `slug`, `image`, `excerpt`, `body`, `published_at`, `created_at`, `updated_at`) VALUES
(1, 1, 3, 'Beatae quae eum ipsa.', 'iure-adipisci-ut-et-id', NULL, 'Ad beatae cupiditate optio esse recusandae tenetur dolor dolorem sint totam non sunt debitis non voluptatem labore in odio dolorem doloremque.', '<p>Laborum neque suscipit consequatur ad necessitatibus. Sit alias sint quia ut omnis nobis. Quia sapiente sit eveniet qui vel.</p><p>Maxime commodi eligendi magnam necessitatibus. Accusamus est facilis error odit quos.</p><p>Aut soluta quia omnis hic possimus. Tempora ex hic sed odio voluptate qui cupiditate. Omnis aliquam voluptatem enim velit minus occaecati. Assumenda facilis dolorem praesentium recusandae hic voluptatum.</p><p>Ad voluptatem sit quas. Ipsa consectetur rem vel est. Veniam fugit perspiciatis in magni. Magni temporibus consequuntur suscipit sit est voluptatum.</p><p>Eaque quidem quia explicabo voluptate modi quia. Dolores dolore voluptatem officiis. Recusandae autem vitae ut. Non velit ad soluta sed eligendi vel. Asperiores quidem nobis et in.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(2, 3, 2, 'Corrupti dolore laborum ipsa vitae necessitatibus quis et veniam.', 'ut-ratione-sunt-aut-nobis-dignissimos-similique-quo', NULL, 'Est beatae necessitatibus tenetur rerum eos optio suscipit quaerat aut nisi quo maxime consequatur eaque quos quam quam.', '<p>Voluptatem earum cum vero doloremque accusantium. Asperiores itaque et doloribus illum. Ipsum id minima sequi. Quo quidem ea perferendis quia.</p><p>Eius qui amet sit magni hic aut doloremque. Aliquid aut eaque deserunt. Nam dolorum nulla architecto blanditiis. Adipisci qui esse sapiente cum.</p><p>Mollitia porro est fugit officia sed reprehenderit praesentium. Repudiandae necessitatibus veniam qui fugiat. Blanditiis aliquid esse cumque ea neque doloremque voluptatem minus. Assumenda accusantium repellendus aut hic.</p><p>Quia sint ratione illo. Amet nam quis aut animi. Enim delectus ut est libero eligendi quidem. Quae eligendi doloribus magnam sed omnis recusandae magni.</p><p>Ut veniam qui nostrum dolor eos mollitia veniam dolorem. Inventore quasi non quam qui eum tempora. Voluptas itaque distinctio consequatur dolorem.</p><p>Pariatur quo alias voluptate inventore natus. Occaecati optio et quo culpa. Id commodi rerum veritatis dolor nihil accusantium vitae.</p><p>Earum id dolores mollitia ex consequatur. Voluptatum natus id rerum minus modi ratione aut beatae. Iusto eum eius eum at ratione. Necessitatibus voluptatibus voluptate dolores quia excepturi.</p><p>Veniam incidunt corrupti qui odio impedit voluptatem enim. Ipsum mollitia quia et nesciunt. Voluptatum nobis expedita aperiam officiis est et. Laborum ut necessitatibus qui eum dolorem et.</p><p>Eaque vel quod veniam explicabo ipsa. Voluptas explicabo facere corporis.</p><p>Aliquid omnis qui minima expedita harum deleniti. Aliquam ea incidunt iste aut natus.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(3, 2, 1, 'Consequatur et reiciendis eos sed.', 'itaque-porro-dolore-possimus-culpa-quaerat-voluptatum', NULL, 'Fugit minus et harum enim nam culpa corporis vero impedit laborum dignissimos quam a quo voluptatem maxime at dolor similique amet at.', '<p>Sit illum et quos suscipit ut. Facilis nam enim qui veritatis. Et consequatur cupiditate corporis accusamus. Natus magni libero earum eos laborum et.</p><p>Pariatur placeat voluptas nihil similique iure accusantium neque. Illum nihil eum earum. Cum cupiditate voluptatem harum laboriosam necessitatibus. Distinctio blanditiis illo recusandae placeat quasi officiis.</p><p>Magni quo laborum perspiciatis molestiae mollitia. Tempore in quia voluptatibus officiis.</p><p>Qui aliquam voluptatem quia iste aut maxime. Dolores beatae eos velit nulla ut consequatur. Sed aliquam temporibus quibusdam hic. Quas libero qui omnis perferendis exercitationem pariatur exercitationem sequi.</p><p>Quisquam doloribus ut quam incidunt neque similique asperiores et. Ut porro accusantium officiis. Laborum dolorem et ullam qui libero. Incidunt eius et aut animi unde fuga.</p><p>Vero molestias maxime deserunt illo dolores. Facere dignissimos magnam alias et quia iusto vero. Velit optio qui odio est.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(4, 4, 3, 'Et rem fugiat facilis iusto aut nesciunt quod et.', 'aut-consequatur-maxime-occaecati-sint-qui-voluptatibus-sint', NULL, 'Sed omnis quibusdam nam qui et aut illum sapiente nam dicta nihil esse voluptatibus et voluptatem velit nesciunt asperiores aut voluptas quia asperiores sint cupiditate consequatur quam debitis voluptas quia hic minima doloremque.', '<p>Omnis consequuntur delectus odit doloribus saepe. Maiores aliquam sed totam ab non pariatur et. Sint possimus est modi neque.</p><p>Nihil totam ad omnis dignissimos suscipit voluptatem. Mollitia dolor et sit corporis ipsum consequuntur. Tempora at vel illum. Deserunt placeat impedit omnis sint.</p><p>Recusandae id eum reiciendis optio consequatur est omnis mollitia. Autem officiis sint exercitationem quis et corrupti. Voluptatem voluptas exercitationem vel quod non illo.</p><p>Consequuntur commodi dignissimos natus recusandae unde quos cupiditate. Et et aut delectus qui laboriosam provident architecto.</p><p>Natus aut ut vel nulla. Saepe unde quia inventore aperiam. Quasi aperiam tempora in odit neque et ullam. Dicta quaerat et quaerat nulla ratione totam sit.</p><p>Adipisci aut et autem est culpa quis. Qui molestiae quaerat eos dolores quis. Ut impedit rerum repellendus et repellendus fugit optio. Est velit tenetur dolor expedita.</p><p>Et iste eveniet eum mollitia sunt. Rem qui molestiae magnam sit sit consequatur commodi. Autem similique voluptas ut voluptatem perferendis enim numquam.</p><p>Et et nobis laborum minus culpa. Aperiam alias quidem nostrum veritatis delectus.</p><p>Atque magnam quas saepe consequatur ducimus. Dolore nisi quis sequi ut aspernatur exercitationem odio. Incidunt quasi ex impedit labore qui distinctio.</p><p>Aliquid ipsa fuga earum delectus et vel omnis. Aliquid quae ratione cupiditate ut. Saepe quidem asperiores quam eum. Vero recusandae dolorem suscipit sed voluptatem exercitationem molestias.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(5, 4, 1, 'Hic eos eum accusantium quis corporis quia laboriosam reprehenderit nihil suscipit est at enim.', 'facilis-aspernatur-voluptatem-doloremque-expedita-autem-deleniti', NULL, 'Nihil qui accusamus quae dolorum perferendis ex nesciunt consectetur eum explicabo natus ut.', '<p>Consectetur enim consectetur officiis vero sed. Aut aspernatur eius dignissimos.</p><p>Magnam ut est animi commodi minus ut eum. Et modi molestiae ab quaerat incidunt.</p><p>Rem illum quod quo minima tempore. Iste quod officiis maiores rerum quis voluptatem possimus. Sed consequatur animi soluta nemo ut.</p><p>Minima dolores dolorem vel exercitationem quam quaerat. Sit quos totam voluptas itaque labore. Ea quia eius tenetur aut ad possimus earum.</p><p>Est unde voluptatem aut laboriosam a atque incidunt. Qui qui et distinctio eius dicta modi. Nulla maiores aperiam voluptas deleniti deserunt error. Voluptas earum error asperiores tenetur qui exercitationem culpa.</p><p>Hic blanditiis aperiam recusandae ea. Ut aut nesciunt voluptate corporis dolorem ea. Quia qui dolorem dolore autem.</p><p>Illum eum possimus numquam rerum omnis earum. Molestiae facere ut maiores minus harum culpa. Porro qui ea est nihil qui nulla aspernatur quod. Tempora tempora commodi eos et similique quisquam.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(6, 4, 2, 'Ea exercitationem molestiae dolor quidem.', 'est-quam-numquam-et-expedita-aspernatur-minus-assumenda-possimus', NULL, 'Et itaque aut sapiente ipsam iste asperiores rem reprehenderit accusamus laudantium corrupti qui eos excepturi quos culpa dignissimos quis quos ea corrupti facere assumenda.', '<p>Iste eos ea similique qui veritatis minus. Cumque laborum nulla cum quo in.</p><p>Nihil quaerat quod facere corporis aliquid eum dolores. Ducimus quam sunt sed iste error. Dolorem a harum eos architecto ut dolores magnam repellat. Qui veritatis deserunt et ad saepe.</p><p>Quam voluptatem eum ab ut odit aperiam iusto. Praesentium sapiente libero mollitia exercitationem voluptatem. Ea dolorum deleniti voluptatum.</p><p>Nobis consequuntur quis est dolorum. Doloremque suscipit excepturi aliquid animi. Quos omnis ea fugit unde sint ipsum earum. Cumque non quae soluta et aliquid.</p><p>Est nisi et totam vero. Ut quidem incidunt quasi. Omnis ut doloribus quidem reiciendis. Consequuntur et deserunt eos qui.</p><p>Voluptas est minima sit est saepe. At et explicabo molestias voluptatem cupiditate atque commodi. In est quibusdam autem nisi aut. Velit qui occaecati nesciunt consequatur at rerum.</p><p>In perferendis doloribus saepe quis et sit ut itaque. Aut vitae id eveniet et.</p><p>Sint at unde nulla veniam voluptas et. Fuga unde corrupti hic iure maiores voluptas rerum. Alias rerum est nam odit officia. Id et illo quia adipisci.</p><p>Architecto quisquam pariatur officia omnis dolor quia odio sed. Voluptatem temporibus enim non totam enim. Ut aut repellat qui sequi autem dolor.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(7, 4, 1, 'Inventore eum nostrum at consequatur odio et voluptatum eligendi error.', 'quidem-autem-omnis-distinctio-qui-placeat-officiis-nemo', NULL, 'Eius ullam non atque sunt non quae et natus est repudiandae et alias fuga iusto nihil est qui reprehenderit architecto dolorem enim nisi non rem ut.', '<p>Fugiat iusto eligendi quis et quisquam explicabo. In iusto quam iusto minus est sit aspernatur. Facilis fuga minima velit deleniti ad dolores odio. Ut aut repudiandae distinctio ut blanditiis est.</p><p>Velit aspernatur ab et rerum voluptas esse et. Quia odio explicabo similique non ut eligendi omnis. Officia deleniti et aut pariatur. Fuga sed blanditiis modi at.</p><p>Molestiae culpa atque corporis sed commodi illo. Nisi omnis vero minus ullam saepe. Reiciendis qui deserunt perferendis quaerat dolorum aperiam. Doloremque dolorem voluptatibus culpa non.</p><p>A quam aperiam quo sed non ipsa sapiente. Unde consectetur provident magni quod saepe voluptatem voluptas. In possimus unde enim ut voluptatem aspernatur. Magnam laborum rerum enim amet nihil omnis.</p><p>Consequatur voluptatem voluptas quae et et cumque ut vero. Aut veritatis est qui explicabo quo hic. Magnam reprehenderit alias est.</p><p>Deserunt quod qui architecto qui. Id accusantium dolorem omnis eum quo et. Corrupti quae sed harum qui non magnam nesciunt. Sequi asperiores doloribus ipsum natus.</p><p>Saepe omnis et distinctio eaque. Explicabo dignissimos at est. Porro amet quisquam molestiae eos dolorum ut.</p><p>Praesentium nulla officiis veniam suscipit blanditiis. Et voluptatem recusandae quae excepturi ut asperiores. Omnis sit cum magnam et voluptas velit. Eum maxime error assumenda officiis.</p><p>Occaecati molestias odit numquam. Magnam sequi autem voluptas. Et aliquid saepe aut quia. Omnis eaque nobis dolor hic ab cum nobis rerum.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(8, 1, 1, 'Voluptate explicabo illum dignissimos est earum.', 'eum-voluptate-est-harum-aut-officiis-et', NULL, 'Et suscipit aut voluptas omnis aut omnis expedita ut voluptatum nam numquam quaerat explicabo impedit sed corrupti eaque doloribus provident qui explicabo asperiores perferendis voluptatum repudiandae libero praesentium in placeat itaque qui id corrupti.', '<p>Et modi sint rerum. Pariatur perferendis velit mollitia laborum consequuntur qui dolorem. Quidem sint rerum nihil odit enim voluptatibus. Nesciunt ut sapiente veritatis dolor molestiae vitae.</p><p>Dignissimos non nobis soluta officia eum enim minima. Quas accusamus quos quam ab qui recusandae. Dolorum nulla soluta itaque magnam in est quia.</p><p>Incidunt consequuntur sequi nam quod dolorem dolores eum. Mollitia dolore nisi a inventore blanditiis optio et. Ipsum facilis magnam itaque quis ipsa. Aut doloremque eveniet rem sint.</p><p>Nisi vel non ipsum facere pariatur rerum dolores. Odit itaque officiis sed recusandae non doloremque reprehenderit culpa. Id sint reprehenderit nisi quas. Occaecati aperiam praesentium reiciendis reprehenderit.</p><p>Et provident quibusdam nostrum delectus. Excepturi impedit impedit tempora qui. Quos temporibus quia ut et exercitationem aut. Voluptas sunt repudiandae totam sed eaque nisi.</p><p>In rerum optio fugiat aliquid dolor. Quod eum qui quis harum. Unde doloribus similique et esse earum.</p><p>Odio sunt et consequuntur aut exercitationem aut neque. Et ipsa laudantium dolorem deleniti facere aliquam. Qui cum neque aliquam aliquid repellat mollitia. Consequatur quasi architecto alias nobis.</p><p>Aut quis est voluptatem magnam enim est. Blanditiis ut ut aut quasi voluptas deserunt. Qui eum officia est ut nostrum est. Rerum quas voluptatem rerum.</p><p>Laboriosam eos quia quia vitae sapiente rerum aut. Tenetur necessitatibus laudantium placeat. Illum unde nam voluptatem facere voluptas qui. Enim numquam velit a voluptatem.</p><p>Temporibus consequuntur velit soluta explicabo. Quis quae sunt cupiditate. Dolor mollitia dolorum magni molestias sit rerum suscipit.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(9, 4, 3, 'Iure autem dolor sit nemo.', 'accusantium-quibusdam-aut-est-a-nemo', NULL, 'At voluptatum rerum dolorem ex iure eveniet hic distinctio deserunt perspiciatis dicta soluta alias et qui ex voluptas enim dolor eum ipsum error voluptatem unde excepturi.', '<p>Dolor ut quos nihil eos qui dolor. Quos consectetur est voluptas non. Cum necessitatibus eius veritatis.</p><p>Quod nihil quo nam sed maiores enim. Dolor rem doloremque dicta qui veniam. Fugiat eius reprehenderit facere.</p><p>Amet et consectetur velit laborum a ea nobis. Neque magni totam esse quis iure est. Tempora a fuga molestias id magni aut perspiciatis ipsam. Cum sunt voluptate in assumenda tenetur eos.</p><p>Est harum reprehenderit ut. Esse quo alias error ea voluptatem. Porro aliquid voluptatem rerum quam laudantium.</p><p>Ut sed aut voluptatem quo provident porro. Voluptates provident alias aut suscipit. Recusandae quae qui in incidunt et non totam. Distinctio animi officiis magni optio iusto.</p><p>Delectus omnis ut cupiditate dolores itaque et. Cupiditate nihil rerum quaerat temporibus in. Autem quis ipsum voluptatum. Quia ratione tempora dolor voluptatem qui quo itaque neque.</p><p>Nobis in illo nihil commodi. Dicta voluptatum est est. Impedit exercitationem sequi ad officiis dolore minima assumenda.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(10, 5, 3, 'Alias saepe et quisquam qui aliquam voluptatem alias non tempora voluptate porro.', 'enim-qui-iste-voluptatibus-quia-consequatur-deleniti', NULL, 'Rerum voluptatem necessitatibus voluptatem non perferendis minima deserunt est commodi ea ducimus provident natus iure autem consectetur sunt ea recusandae quasi consequatur ab inventore perspiciatis quisquam consequatur ut rerum.', '<p>Enim error ipsa repudiandae tenetur sequi et cumque. Sint ipsam enim excepturi laboriosam aperiam esse expedita sint. Et molestias ex maiores itaque animi.</p><p>Voluptatem veritatis asperiores architecto quam laboriosam. Ut nesciunt incidunt aut enim. Nemo aut inventore et temporibus totam et exercitationem. Et ut cupiditate autem ea aut iure.</p><p>Sunt ex dolore vitae quam. Aperiam eum inventore cupiditate ullam sit molestias. Fugit consequatur quas at quis consequatur non corrupti. Aut dolorum optio tenetur et sed.</p><p>Magnam illo voluptatibus deleniti nam rerum. Blanditiis magnam sint ullam architecto est et. Dignissimos ad non molestiae blanditiis et non aut. Ut nemo vel in tempore.</p><p>Qui odit iure modi sint et. Cumque quia voluptas est culpa. Et repudiandae deleniti facere blanditiis molestiae.</p><p>Sed esse ut voluptatem earum provident eaque aut. Aut architecto incidunt dolor esse. Vel ipsum est dolore et mollitia. Saepe rem sunt praesentium eos quidem.</p><p>Qui non explicabo suscipit dolorem. Facere veritatis esse eum architecto. Officia inventore debitis est ratione. Animi corrupti sit saepe iste enim aliquam vitae aut. Et soluta et dolor praesentium dolor architecto et possimus.</p><p>Est nemo reprehenderit vero ea corrupti odit. Eaque exercitationem exercitationem consequatur omnis est recusandae. Qui dolor eligendi nihil sit maiores natus quae nesciunt.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(11, 3, 1, 'Atque autem odio nihil consequuntur labore nostrum est.', 'quia-nobis-ullam-sed-asperiores-officiis-repellendus-modi', NULL, 'A voluptates magnam voluptatem distinctio incidunt est perferendis quia optio molestiae rerum consectetur dicta unde.', '<p>Ut esse et magnam dicta animi occaecati beatae cupiditate. Ipsum id quia voluptas reprehenderit. Minus adipisci explicabo voluptatum nostrum aliquam.</p><p>Vitae odit aut deserunt consequatur repellat earum. Unde culpa tenetur nostrum. Nemo sunt excepturi officiis omnis illo.</p><p>Voluptatibus et autem doloribus ut. Accusamus quos non voluptas qui laboriosam. Consequatur sit in repellendus dolor nam sed velit voluptatem.</p><p>Velit aliquam facilis cum commodi illum dolores. Ducimus sint praesentium temporibus quia dolorem. Inventore natus exercitationem ut repellendus ipsa dolor quia.</p><p>Quidem praesentium exercitationem aut quae iure omnis dolores. Voluptatibus magnam soluta nisi aut quidem.</p><p>Qui deserunt qui assumenda nam totam et. Quisquam possimus fugiat doloribus dicta illum. Sit dolorem possimus molestiae recusandae perspiciatis.</p><p>Et soluta vel quisquam eius qui amet. Et vitae quos quam harum.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(12, 1, 1, 'Dolorum et nulla quasi.', 'vero-et-voluptatem-non', NULL, 'Cumque nemo tenetur sit esse alias perspiciatis aut et ratione mollitia qui iusto perferendis aut distinctio soluta molestias sunt aut eligendi eius et.', '<p>Animi est non numquam. Quis at repellendus sunt. Odit neque et molestiae. Maxime ut accusamus animi fugit non iste recusandae.</p><p>Sit nulla sed natus non debitis molestiae consequuntur. Vel ex molestias et quia rem hic qui. Id pariatur quia quia cum delectus quas fugit. Dolorem nihil et quia vel vel provident corporis aperiam.</p><p>Nam tempore quisquam dolor ea sed. Molestiae quia repellat illo similique ipsa minima cupiditate. Qui odio sint possimus voluptates dolores cum odio. Necessitatibus quaerat incidunt velit.</p><p>Numquam nulla saepe consequatur ab error. Omnis numquam dignissimos architecto non. Voluptas debitis at ipsa. Excepturi vel est asperiores magnam dolores.</p><p>Explicabo aspernatur similique eaque voluptatem nobis. Exercitationem harum dolores eum quisquam quisquam est excepturi. Aut facilis saepe expedita natus.</p><p>Ut ea est expedita et. Labore corrupti dolore ut placeat. Est molestiae et ea nulla eaque quia.</p><p>Quam dolor recusandae beatae aut fugiat. Quia eos minus dolores iste dolorem mollitia ab. Facere aut velit facere quae atque saepe doloremque ipsum.</p><p>Voluptate pariatur eligendi eius iste aliquam dolor. Deserunt sequi quis iure et.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(13, 4, 1, 'Nobis ipsam vel qui.', 'dolorem-error-ullam-laborum-laborum-ea-in', NULL, 'Aut deserunt repellat deserunt sint ullam asperiores amet omnis quo cupiditate eum velit illum optio repudiandae enim et non est alias quam ea mollitia est perferendis.', '<p>Possimus dignissimos magni adipisci fugit. Sequi quia consequatur iusto dolores. Voluptas corrupti recusandae totam incidunt fuga. Nisi repellendus sequi recusandae in voluptatem quia harum.</p><p>Sapiente quis neque ducimus quia tempore nihil repudiandae. Officia quia quo a adipisci. Et dolorem accusamus architecto corporis. Provident dolorem omnis id et optio sapiente qui.</p><p>Modi voluptatum reiciendis et nihil. Commodi provident impedit placeat quibusdam omnis. Et sint illo ratione molestias excepturi non. Eius voluptas sint nulla consequuntur omnis quos. Incidunt blanditiis adipisci qui nesciunt.</p><p>Eos ut ullam error cum. Impedit et iure quia deleniti. Iure sint laborum deserunt dolores. Beatae voluptatibus repellat dolor.</p><p>Qui earum consequatur tempora reprehenderit omnis dolores. Sed autem dolores nisi omnis illo earum ad. Rerum non qui voluptatem.</p><p>Sed id quia eaque corrupti. Blanditiis non voluptatem ad. Illo quia et rerum dolore. Aut ipsa ut et aut.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(14, 3, 1, 'Velit placeat distinctio nam repellat molestias.', 'suscipit-voluptatum-incidunt-corporis-aut-repudiandae-autem', NULL, 'Omnis odio sed qui libero fugiat deleniti incidunt sed aut incidunt dolores autem natus ipsa voluptas est voluptate et quo non.', '<p>Ut aut fugiat deleniti ullam minus consectetur. Sequi ex unde quis dolores quia autem. Maxime omnis porro a omnis earum perferendis perspiciatis.</p><p>Et quod consequatur fugit eum. Quis porro dolores pariatur et aut. Sed rerum quam eveniet aut soluta soluta optio.</p><p>Inventore maiores repellendus eum hic. Quaerat odio nam commodi ut maxime. Explicabo est quod qui quo maxime totam aut. Sed dignissimos et laboriosam veritatis velit impedit.</p><p>Nobis in animi porro necessitatibus explicabo aut distinctio enim. Expedita sint iure nobis. Dolorem et sequi et officiis occaecati.</p><p>Ipsa modi quia velit suscipit. Aut voluptatibus delectus dicta error. Eaque earum id rem itaque dolor et sit.</p><p>Quia nostrum aspernatur libero et. Non minima sit occaecati itaque qui doloremque. Explicabo sint suscipit voluptatibus ab.</p><p>Voluptate et ipsam cumque reiciendis distinctio tenetur. Quia cumque praesentium tenetur velit sed perspiciatis molestias. Quo consectetur praesentium ipsum rerum quae sed assumenda. Impedit atque est eos quas tenetur.</p><p>Voluptatem dolorum itaque qui recusandae exercitationem iusto qui. Dolore ratione aut alias accusamus perferendis rerum. In et molestiae inventore incidunt.</p><p>Repudiandae omnis nisi aut aut. Quam ipsam perspiciatis et placeat qui est. Et recusandae ducimus impedit et et. Corrupti unde consequatur provident alias tenetur.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(15, 3, 3, 'Sit quis molestiae omnis perspiciatis architecto aut et architecto ipsum quia voluptatem.', 'sequi-alias-cupiditate-eos-ullam-vitae-aliquid', NULL, 'Minus debitis necessitatibus maxime quasi enim in occaecati sed quia libero commodi pariatur maiores minus et dolorem porro quam numquam.', '<p>Ut deleniti dolorum inventore ut aut et numquam non. Accusantium ut autem ut omnis qui repudiandae eveniet eligendi. Velit consequatur laudantium magni iste. Facere aut est voluptate possimus.</p><p>Libero debitis cupiditate inventore minima nihil id qui. Sed vitae repellendus voluptas occaecati magnam. Dolorum magni autem voluptate maiores velit.</p><p>Amet doloribus in aut labore sit nemo omnis dicta. Consectetur quasi a earum modi atque praesentium. Aut et distinctio maxime nobis. Hic enim harum voluptatem sunt qui.</p><p>Ad error non reiciendis vel omnis. Reprehenderit in est fuga sed nihil consequatur. Sit sint et quisquam ipsum ea. Et rem tempora et harum aspernatur quasi optio.</p><p>Sit animi esse quis nobis. Ea sapiente sequi architecto. Minus officia molestias quaerat.</p><p>Aut adipisci corrupti expedita consequatur. Consequuntur eum dolore atque autem. Quis debitis et quibusdam maxime.</p><p>Sed quidem illum voluptas nobis ipsam maiores cupiditate molestias. Maxime est dicta et. Earum voluptatem iure ut possimus dolor.</p><p>Veniam cum sapiente inventore dolor. Cupiditate deserunt voluptas sapiente et suscipit et est. Veritatis vero magnam delectus dolores est enim.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(16, 1, 2, 'Occaecati est molestiae placeat non ut distinctio.', 'esse-maiores-officia-cupiditate-exercitationem-fugiat-aut-tenetur', NULL, 'Id doloremque beatae neque sed rem laboriosam sint doloribus placeat quo quis et dolores quod et quia maxime dolores omnis quo id deleniti molestias illo quod eos.', '<p>Consequatur quo officiis sint aut iure optio nulla est. Voluptatem quia perferendis voluptatem exercitationem quos. Ea enim eaque et consequuntur ad. Molestiae rerum impedit fugit autem et vel natus.</p><p>Eius ut a sed quas dicta iusto. Maxime est voluptas quis ut sint dolore inventore. Voluptatum hic rerum ducimus veniam quibusdam dolores libero.</p><p>Necessitatibus optio accusantium pariatur aut. Suscipit dolores vel rerum quibusdam. Ducimus aperiam facere quo nam. Quod sunt doloremque rerum ut facilis.</p><p>Incidunt reprehenderit aliquid doloremque perspiciatis veritatis eligendi saepe. Esse ad esse error quis eaque natus aliquam recusandae. Molestiae itaque et sunt expedita officiis alias culpa. Est sint consectetur velit ipsam non ut.</p><p>Ipsa et libero atque eum. Sed pariatur et dolor quia voluptates non. Placeat nam et repellendus sequi. Ad sed sed ullam maiores et.</p><p>Nam aspernatur illo corrupti minus. Sunt esse dolor natus delectus consequatur odio qui. Ut error est est saepe voluptates placeat aut iure.</p><p>Reiciendis corporis sunt eveniet. Accusamus dolores itaque ducimus quia incidunt nemo. Illo consectetur quis occaecati doloribus quam. Beatae animi illum expedita nam aliquid.</p><p>Deserunt et eum facilis distinctio aliquam ut recusandae. Quae at nihil cumque voluptatum assumenda neque esse. Dicta perspiciatis autem voluptate.</p><p>Velit aut dolorem rerum aperiam dolor praesentium nam voluptas. Illo eum facere dolor sequi reiciendis tempore. Corporis ut fuga soluta at harum molestias quidem. Dignissimos eveniet tempore distinctio illum sit sunt necessitatibus voluptate.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(17, 3, 3, 'Quia odio officiis molestiae dolorem fugiat ut accusamus natus.', 'amet-ea-dignissimos-quos-perspiciatis-voluptas-ea-rem-in', NULL, 'Alias delectus eveniet veritatis et autem architecto ut et provident dolor magni mollitia qui deleniti vitae odit aspernatur voluptate voluptates explicabo facilis sed numquam velit ea repellat id natus.', '<p>Fugit modi temporibus facere inventore soluta eligendi error rerum. Deleniti harum perspiciatis iure aut ut. Consectetur esse impedit voluptatem autem repellat. Dolor iure enim placeat numquam nesciunt.</p><p>Soluta a eum corporis et. Labore quod rerum voluptas quas dolorem ullam atque. Earum illo molestiae sit amet.</p><p>Et saepe sed vel in modi tempore. Distinctio sunt et dolore eligendi architecto cupiditate consectetur maxime. Cum quas atque quos ipsum sed esse. Voluptates ipsa atque unde possimus. Quo modi ratione debitis quam reiciendis eum.</p><p>Perferendis consequatur qui aut numquam quis sed. Veniam enim omnis suscipit error ut iusto repudiandae. Voluptates quisquam nesciunt voluptatem cupiditate enim quod ipsam quaerat. Minima eum est sint voluptates explicabo. Numquam ut id quisquam odit tempora fugiat quaerat.</p><p>Ut quas consectetur id doloribus dolore. Quas quia sed et natus ullam. Fugit architecto at aperiam cumque sint doloribus quod. Illo vero et veritatis eius quos sint.</p><p>Nulla ea enim unde voluptatem delectus. Earum rerum unde beatae qui. In dignissimos soluta minima excepturi fugiat officia.</p><p>Sit est autem et molestiae cupiditate. Autem omnis dolorem saepe officiis id vel laborum voluptatem. Iusto dolor dolores recusandae odit.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(18, 3, 1, 'Facilis quam ut nesciunt eum rerum ducimus consequatur id ab.', 'vero-dolorem-sunt-odio-nulla-ab-vel', NULL, 'Et nihil enim dolorem nam facere quae delectus consequatur ut cumque aut est iure esse illum saepe aut omnis facere fugiat laudantium sapiente veritatis.', '<p>Exercitationem quisquam consequatur cumque nobis sit itaque. Voluptas aperiam vel ut ut inventore ut. Est eum culpa tempora voluptatem in unde. Molestiae assumenda qui labore voluptates soluta totam.</p><p>Sapiente voluptas dignissimos esse explicabo voluptatem corporis. Suscipit facilis et enim doloribus voluptatem repudiandae corrupti.</p><p>Dolore temporibus est autem. Neque dignissimos quidem et delectus. Rem omnis perferendis sint sed error quia est. Porro iure labore occaecati soluta omnis explicabo aliquam necessitatibus.</p><p>Sit debitis quae aliquid alias odit impedit neque. Aut aut impedit aperiam quasi id. Pariatur in consequatur facilis molestiae pariatur autem pariatur.</p><p>Dolorem quae molestias ducimus. Saepe cumque voluptatem quo aperiam ut reiciendis. Saepe architecto qui voluptatem commodi unde.</p><p>Enim dolores id autem reiciendis. Illo sunt ut quia quis et et consequatur. Et pariatur et et quia aut tenetur velit ipsum.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(19, 4, 1, 'Rerum voluptatem in quas eligendi debitis dolores est.', 'ratione-enim-inventore-sequi-ea', NULL, 'Laudantium nemo nisi eveniet accusantium sint fugit sed sit nihil ea quis et quia sapiente quo quia quo.', '<p>Quia aut sunt sunt dolores. Perferendis eum voluptas optio ut voluptatem. Rerum et ut soluta illo.</p><p>Nam aliquid perferendis possimus assumenda delectus voluptatem iure. Laborum vitae repudiandae expedita est omnis. Eos rerum nesciunt illo dolores magni aliquid et. Minima sunt iusto provident pariatur deleniti.</p><p>Rerum amet et deserunt eaque dignissimos. Ut ipsa dolor natus consequatur aliquid libero. Autem nam et eum est reprehenderit soluta eos aspernatur.</p><p>Consequatur commodi assumenda modi. Autem dolor quisquam sint quis. Autem possimus veritatis sapiente quo quisquam exercitationem sed. Laudantium distinctio dolor temporibus.</p><p>Maxime maiores fugiat quam aut. Cum dolores ut vitae tempora et aut. Qui et sint nulla enim ut. Praesentium unde veniam repudiandae sint at. Sed rem quibusdam nemo.</p><p>Qui ratione fuga quia iste aliquam molestiae magnam. Velit rerum occaecati delectus et reiciendis eos voluptas. Et neque distinctio sed qui incidunt.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(20, 2, 1, 'Error earum sit consectetur culpa qui iusto.', 'mollitia-ducimus-voluptatibus-harum-quasi-eos-in-inventore', NULL, 'Laudantium provident qui repellat adipisci omnis quam sed voluptatem nulla alias fugiat beatae occaecati optio velit alias vel vel at est.', '<p>Aperiam quia et nemo. Placeat excepturi expedita architecto et nobis dignissimos.</p><p>Vero iusto qui minus quia. Perspiciatis reprehenderit sit dolorem aperiam sit a quidem. Consequatur error ut quis dolores qui maiores. Voluptas ut id est corporis qui aut placeat voluptate.</p><p>Repellendus in cum autem rerum in at. Dicta accusantium architecto laboriosam id aperiam ut. Quidem quis voluptates explicabo accusamus asperiores.</p><p>Natus odio ex est expedita. Rerum ut inventore impedit suscipit ea ea vel officia. Quo corporis autem quod voluptate est veritatis.</p><p>Nihil suscipit exercitationem omnis ut excepturi corporis eveniet. Asperiores dolorum rerum nesciunt a eveniet culpa. Dolorem deserunt mollitia delectus modi quisquam exercitationem. Voluptas quia quia porro nostrum repellat vitae facere.</p><p>Aut corrupti amet dolorum aspernatur unde. Libero quia nam et et saepe delectus sunt labore. Sit soluta incidunt iste. Quaerat sapiente rerum sint a rerum.</p><p>Qui laudantium voluptatum esse. Veniam rerum quibusdam magnam est vel et sit. Nam dicta dolores perspiciatis iure rerum ut et. Eos aspernatur maiores dolor inventore quam qui perferendis suscipit. Nisi laborum quidem fugit iure dolorem quas sunt.</p><p>Necessitatibus nihil aut ad et. Repudiandae mollitia commodi quia modi sit. Non qui velit libero qui assumenda maiores.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(21, 3, 1, 'Quam quia culpa ea optio rerum.', 'sed-laudantium-qui-in-molestiae', NULL, 'Voluptatem tempore enim voluptatem excepturi nihil porro qui alias facere dignissimos mollitia distinctio corrupti asperiores possimus magnam aut impedit harum consequuntur voluptatem tenetur ab aut distinctio aspernatur blanditiis aspernatur dignissimos reprehenderit.', '<p>Rerum maiores officiis nisi consectetur quaerat velit facere. Tenetur placeat impedit ratione veniam. Necessitatibus quis quo doloremque provident illo et pariatur. Cumque iure nemo est distinctio.</p><p>Et saepe perferendis dolor quia id suscipit. Optio at eligendi vel libero impedit. Quidem expedita et provident quam dolorem aut non.</p><p>Nisi harum possimus excepturi eos aut ea. Voluptatem veritatis quos quas ipsam sed. Est omnis tenetur vel ex iste nam sapiente reprehenderit. Et perferendis id hic qui molestias rerum consequatur.</p><p>A nemo inventore qui rerum. Veniam reprehenderit corporis debitis optio sunt ut. Aut incidunt laborum itaque.</p><p>Vero doloribus id quis illo provident possimus maxime. At praesentium incidunt error eligendi ut asperiores. Aut perferendis voluptatibus quo minima iusto qui. Est ut sunt libero non omnis labore quidem dolore.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(22, 4, 2, 'Enim ratione id ut et ex consequuntur.', 'aut-eos-soluta-facilis-et', NULL, 'Aliquid odio facere iure voluptatem quos ducimus mollitia veniam dicta libero doloremque qui voluptas cupiditate beatae porro qui consequatur minus vel ipsa voluptatem accusamus accusamus distinctio.', '<p>Esse maiores nemo dolores accusamus est porro. Quas officiis expedita provident qui consequuntur debitis. Voluptatem dicta ea pariatur dicta.</p><p>Asperiores incidunt odio at. Praesentium error perferendis aut quae veritatis in dicta. Quia molestiae magni odio odit sed dicta odit consequatur. Eos id alias laudantium atque est et.</p><p>Repellendus ipsa sit et et sint saepe. Doloremque repudiandae voluptas quidem incidunt. Amet quo excepturi enim inventore. Natus consequuntur eveniet itaque facere.</p><p>Est dolorum ab et deleniti id laborum maxime. Ad corporis ducimus repudiandae eos inventore. Ut quod ducimus quae eveniet quod eos perspiciatis. Nam ab cumque soluta quas molestiae ut consequatur.</p><p>Ratione in consectetur unde et voluptates sed ipsum quod. Est sed voluptatem voluptates quisquam. Repellendus odit quibusdam reiciendis pariatur doloribus magnam. Nesciunt aut unde aut dolores voluptas blanditiis illum.</p><p>Fugiat vel aut quia adipisci omnis dolorem cupiditate. Doloribus quo similique optio aliquam. Repellat possimus praesentium quasi qui. Optio non distinctio ad sed autem totam.</p><p>Sed nisi consequuntur quod et harum molestias. Reiciendis ad perspiciatis voluptatem inventore atque aliquid. Exercitationem in error natus. Eius at eius sequi enim ex quisquam reprehenderit eligendi.</p><p>Et earum tempore quia accusamus. Repellat qui quis sit ea placeat. Alias sequi ab dignissimos quis debitis quis. Qui amet blanditiis et similique ullam delectus.</p><p>Et earum dolorem ea fugiat quos. Exercitationem deleniti reiciendis quidem sunt sit consequatur. Dolores distinctio aliquam excepturi cumque eos et nobis. Nulla quas blanditiis similique rerum animi optio provident. Voluptates ea distinctio est dolor accusantium molestiae esse.</p><p>Ex ab et quia cupiditate rerum omnis quia est. Accusamus excepturi quidem voluptatem aliquam deleniti quia. Dolor nam nulla qui. Optio blanditiis sapiente consequatur distinctio.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(23, 1, 3, 'Consequatur iusto ea accusantium dolor dolore provident.', 'et-sed-reprehenderit-qui-adipisci-molestiae', NULL, 'Ut veritatis quisquam quo praesentium iste quis natus voluptas necessitatibus consectetur in voluptatem consequatur totam non rerum qui qui qui sit minima libero aut.', '<p>Fuga velit reprehenderit vitae provident atque placeat. Officiis nihil nisi laboriosam. Est debitis reiciendis molestias voluptas consequuntur praesentium dolore.</p><p>Rerum ipsa dicta nemo. Quia sit aspernatur aliquam et voluptas.</p><p>Aliquid non omnis iusto et in debitis sunt. Sit sunt nesciunt amet aspernatur odit eos. Voluptas ea sit cupiditate dignissimos et sint.</p><p>Iste debitis optio sed impedit suscipit aut distinctio. Pariatur rem nobis sint architecto sunt aperiam. Iure expedita voluptates dolorem eos eum similique. Odio enim accusantium accusantium perferendis.</p><p>Accusamus ullam voluptates consequatur. Nihil veritatis accusantium blanditiis ad cupiditate quia. Iste accusamus quo odit quia.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(24, 1, 1, 'Perspiciatis quae voluptatem omnis architecto fugit dicta voluptate ratione veniam doloremque qui.', 'autem-aut-animi-ea-vel-et-est-error', NULL, 'Eius aliquam quia rerum sunt quia numquam sapiente qui iusto iure dolores molestias vitae incidunt dolor.', '<p>Quasi voluptas culpa saepe non quo rem. Eum enim sapiente saepe et ut sequi doloremque veniam. Consectetur quos ut ipsa quos repudiandae beatae.</p><p>Suscipit voluptatem quis ipsum ex voluptate sit. Quis dolor maiores laboriosam ut iure. Maiores velit exercitationem explicabo hic. Aut repellendus officiis ab ad ea.</p><p>Dolor molestiae vero et illo repellat est. Sunt incidunt cumque autem quia quia voluptas. Soluta id esse dicta culpa dolorum alias debitis et. Dolor nihil modi voluptatem sint aut.</p><p>Minus nesciunt eaque aut esse. Officia quia sit qui non dolore. Reiciendis expedita laboriosam aut in sequi voluptates molestias. Corrupti magnam doloremque autem aliquid fugit doloribus voluptates.</p><p>Et ea aut ut commodi. Esse veniam a eum suscipit. Et debitis ipsam consequuntur distinctio.</p><p>Dicta explicabo quod rerum qui quia nesciunt consequatur. Ex sunt corrupti facere blanditiis optio. Nostrum voluptas et temporibus voluptas repellendus voluptatibus quaerat. Doloremque tempora aliquid nihil expedita dolorum id maiores.</p><p>Placeat veritatis neque est mollitia. Reprehenderit amet in sit voluptatem.</p><p>Cumque commodi id sint culpa. Rem officiis odit non ipsam et qui rerum itaque. Rerum aut quibusdam sunt fugiat qui laborum consectetur. Quaerat esse rem doloremque nihil.</p><p>Ex voluptates consequatur nostrum nostrum dolorem. Voluptatem quos quia nostrum. Et esse aspernatur sapiente et perferendis temporibus commodi. Officiis suscipit quis voluptatem error nemo temporibus.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(25, 1, 2, 'Qui expedita quia id delectus consectetur accusamus nihil neque nulla aut.', 'assumenda-quam-quaerat-voluptas-culpa-pariatur-pariatur', NULL, 'Nesciunt dolor deleniti iste non deleniti dolor est ut autem est id cum laborum voluptatum nam atque expedita rerum.', '<p>Facilis recusandae nulla numquam aut dolore. Magni suscipit exercitationem quam dolore quo. Veniam sed totam suscipit quo deleniti ut omnis fugiat.</p><p>Autem ut accusantium optio quae non dolores quia. Dolor qui omnis eaque sunt. Veritatis reprehenderit qui nulla sequi maxime accusamus sit.</p><p>Pariatur iste sunt aut mollitia quo consequatur quasi. Rem qui et ipsum enim perferendis rerum.</p><p>Suscipit voluptatibus officia perspiciatis itaque suscipit quae quae. Recusandae et aut sed autem. Et sit aperiam dicta ut pariatur deleniti. Odit assumenda necessitatibus aut odit facilis.</p><p>Accusantium voluptate perspiciatis occaecati a rem dolorem laudantium in. Veniam atque ad minus eveniet. Exercitationem qui nam ab aut.</p><p>Non est numquam repellendus quo ea ut repellat. Et blanditiis eum voluptatem. Harum sequi non porro pariatur sapiente. Et laudantium nisi dolores corrupti.</p><p>Eaque sit qui provident maxime et officiis. Harum dolorem quam consequatur unde dolorem porro ut. Illo adipisci aut architecto ut cumque in.</p><p>Sit laudantium dicta deserunt ea animi dolorum molestiae accusamus. Omnis eaque quo ratione minima voluptatem iure repudiandae assumenda.</p><p>Dolore iusto autem iste nisi et consequatur. Facilis mollitia excepturi ut voluptates vel.</p><p>Corrupti qui alias eveniet corporis voluptas ratione ex. Illo vel officiis voluptas qui et. Minus sint atque officiis ipsa odit quia officia.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(26, 3, 2, 'Qui perspiciatis corrupti quam laboriosam.', 'eum-est-tempore-velit-inventore-vero-dolor', NULL, 'Amet omnis saepe rem laborum esse qui possimus odio enim neque unde omnis dolorum quia et fugiat laudantium eaque voluptates vel quasi et ut et similique quia.', '<p>Cupiditate et rerum autem error repellendus amet cumque. Quis qui non explicabo voluptas ab. Aut mollitia sint omnis laborum. Enim beatae fugit mollitia error eos nihil et.</p><p>Et architecto reiciendis consequuntur repellendus quibusdam molestiae. Iure qui non quia eum quae perspiciatis. Aspernatur sint quidem repellat cupiditate veritatis sit. Sapiente pariatur cum eius ex et quam.</p><p>Beatae ipsam numquam iusto blanditiis a dolorum fugit. Iusto repellendus nobis non officia nulla totam nihil. Dolorem assumenda nihil fuga aliquid aut sunt.</p><p>Quisquam iure esse expedita harum consequatur consectetur dolorum. Quidem molestias molestiae voluptatibus nihil cum at saepe ut. At quasi amet laboriosam sed voluptate magni ea.</p><p>Animi aut possimus fuga. Incidunt velit blanditiis aut.</p><p>Odit accusantium blanditiis adipisci ut odit dolor. Quam iste ad vero eos. Molestiae fuga soluta in eos quaerat.</p><p>A aperiam velit culpa. Molestias et architecto fuga voluptas doloribus quo. Error ut harum cum neque et veniam eveniet. Sed vero voluptatem repudiandae quaerat consectetur possimus.</p><p>Aliquam possimus reprehenderit alias facere. Eos esse nemo explicabo vero voluptatem. Molestiae ratione maiores natus vel fugit omnis cupiditate. Facilis molestias architecto alias nobis eos.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(27, 3, 3, 'Vel ut eveniet aut voluptas nostrum aut.', 'quis-aut-maxime-tempore-est-qui-minima', NULL, 'Non consequatur cupiditate eum ipsum minima minus animi repellat dicta et alias molestiae sunt ipsa tenetur.', '<p>Tenetur dolor dolores similique natus dignissimos sint. Occaecati facere omnis occaecati voluptatibus et.</p><p>Velit incidunt similique facilis nulla. Aut sapiente et non. Repudiandae odit et et nemo provident autem aut. Provident ut harum totam.</p><p>Eum maxime quibusdam quos. Suscipit corrupti reprehenderit quod atque. Recusandae quaerat omnis fugit laboriosam.</p><p>Omnis ut placeat sit dolores magnam delectus et. Vel aut vel qui fugiat. Rem aut atque fugiat adipisci. Debitis alias voluptatum aut est excepturi ratione voluptas.</p><p>Nobis aut ut consectetur et. Qui enim earum aut. Corporis expedita qui dolores ea a quasi ex quo. Et et et eum velit neque.</p><p>Est et et aliquam dolor recusandae. Aspernatur eos accusantium et atque libero deleniti libero. Sit illum consequuntur dolores praesentium dolore eum voluptatem.</p><p>Minus id voluptas doloremque harum eaque aut fugiat. Quasi explicabo unde aut. Sint illum ad veritatis voluptatem.</p><p>Repellat a id repudiandae impedit sed. Ut eos et minima consequuntur nisi non quod voluptas. Qui et ea dolorem qui eaque. Non quos hic quisquam quibusdam illum aut assumenda.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(28, 1, 2, 'Eaque perspiciatis dolore minima ducimus quisquam facilis aspernatur enim exercitationem.', 'incidunt-veniam-a-pariatur-consequatur', NULL, 'Ducimus eos molestiae et ut sit ut voluptas amet esse fugit qui soluta ut sequi fugiat culpa quo vel porro dolorem dolor distinctio quam quis natus odit culpa animi qui est accusamus.', '<p>Doloribus quis vel excepturi et. Animi consequatur a qui voluptatem nostrum maiores accusamus. Rerum et reiciendis aliquam voluptates placeat earum. Ipsa molestias ullam corrupti ipsa recusandae provident.</p><p>Aliquid ipsam ut sapiente laudantium. Quisquam a non accusantium iure. Dolor aut enim quis repellat aut facere. Velit tempora at itaque.</p><p>Explicabo nobis tenetur non consequuntur qui numquam inventore facilis. Et commodi omnis sint reiciendis ipsam eos. Exercitationem dolore quis eveniet ullam. Et corporis quia recusandae consequatur odio fuga.</p><p>Consequuntur qui dolores consequatur dolores nam qui voluptas. Sed ut praesentium labore necessitatibus suscipit et repellat. Quae quasi aut nesciunt itaque earum vitae. Rerum expedita inventore corporis numquam vitae magni. Dolorem nesciunt facere dolorum sunt.</p><p>Nihil in tempora veniam tempora veniam. Rem et accusantium at provident fugiat. Voluptatem expedita facere beatae corporis et magni labore reprehenderit.</p><p>Dicta saepe architecto hic provident voluptatem impedit tempora. Vitae occaecati qui non ut et. Aut aut quis quo aliquid.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(29, 2, 3, 'Omnis dignissimos atque quis dolore ea atque sit sit.', 'veniam-facilis-sed-quasi-doloribus-cupiditate-molestias-totam', NULL, 'Eaque deleniti autem omnis officia dolores consequatur qui hic consequatur occaecati minima magni in in eligendi et commodi sit libero vero.', '<p>Voluptas qui laudantium sint esse quam est hic. Soluta totam nostrum itaque magnam suscipit magni ipsa. Accusamus aspernatur at eaque est facilis quae.</p><p>Impedit molestias natus veniam consequuntur maiores consectetur. Nobis dolore laborum quis et. Quod commodi vel aut possimus. Voluptas ratione reprehenderit laboriosam iure ab nulla.</p><p>Illo doloribus repellat qui saepe. Saepe odio quia consequatur atque. Numquam est et hic hic illo in vel veniam. Nihil velit voluptate et quia.</p><p>Dolore illo qui repellat voluptas cupiditate. Occaecati est aut sapiente. Ex omnis quibusdam nobis.</p><p>Quidem est iure accusamus aliquid quisquam ipsum quo. Aut enim neque repellendus nihil modi ut commodi id. Nam ut tenetur aperiam amet accusantium. Optio occaecati sapiente facere maxime perferendis minus consequatur consequatur.</p><p>Animi sequi provident quia praesentium. Nostrum iure iste vitae maxime. Vitae quae magnam quia officiis sed totam et.</p><p>Eius aliquam officia blanditiis nostrum qui ea aut ullam. Aspernatur molestias dicta est eum vitae optio et. Et quaerat ab laborum quis. Consectetur sint consequuntur voluptas id cum.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(30, 3, 2, 'Iste ducimus cumque cum possimus.', 'nihil-nesciunt-in-reiciendis-et', NULL, 'Omnis aut quod excepturi et nostrum perferendis voluptatem quis est quos quidem in quibusdam deleniti a.', '<p>Porro illum quis dolorem quia dolorum odio molestiae. Omnis tempora qui labore voluptatem et impedit eveniet. Quasi tempore quaerat velit aspernatur rerum et sequi. Labore nostrum aut enim tempora eaque doloremque.</p><p>Ut fuga quos consectetur unde. Praesentium in et ducimus nostrum dicta et vitae ipsam. Ab recusandae quia harum quia molestias. Consectetur rem amet explicabo sit aut tempore molestiae.</p><p>Dolor sit ut sit fugit ut. Veritatis ex fuga vitae a quam. Facere nihil molestiae eveniet corporis nihil corrupti.</p><p>Odio corrupti laudantium dolores veniam eligendi sed. Consequatur sed nulla placeat reiciendis aut. Adipisci accusantium minima deleniti natus. Exercitationem nostrum ad quod nisi non cum facilis. Consequatur aliquam totam ut quia est consectetur porro.</p><p>Sint illo vero dolor nisi. Nesciunt aut occaecati dolor cumque vel iure beatae. Tempore illum quam nesciunt rem aut cupiditate.</p><p>Tempore perspiciatis impedit commodi minima nihil. Accusamus officiis provident temporibus sed est earum vel repudiandae. Est adipisci accusamus aut ipsum dolores a natus ex. Vero accusantium necessitatibus minima dolor rem eius dolores.</p><p>Quo ullam molestias sed nihil quidem laudantium eum et. Sed id laboriosam voluptatibus rerum. Natus explicabo et saepe tenetur.</p><p>Doloremque quaerat illum sit itaque soluta quas. Voluptatem ut fugiat et voluptatem. Nulla omnis quas necessitatibus odit cupiditate.</p><p>In voluptatem sequi quam et. Itaque omnis explicabo architecto nam velit doloribus et. Autem incidunt possimus similique aut. Ut dolores minus est neque iusto.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(31, 5, 2, 'Quia nam fuga aperiam et laborum omnis harum repudiandae qui ullam beatae.', 'consequatur-sit-impedit-temporibus-et-corrupti-ut-ut', NULL, 'Nesciunt aliquam esse numquam reprehenderit dignissimos impedit et aut voluptatem quia ut voluptates velit nesciunt.', '<p>Quibusdam sed distinctio incidunt dolor. Vel hic optio commodi. Aperiam et aliquid quisquam laborum.</p><p>Est autem deserunt adipisci voluptas impedit consequatur quam. Repudiandae eligendi similique perspiciatis vero eligendi. Qui corporis ut molestiae delectus.</p><p>Voluptas harum accusantium facilis cumque. Qui eos non cum sed sapiente. Officiis est eos fugit doloremque. Maiores totam fuga voluptas deserunt voluptatem quo atque.</p><p>Impedit quos est est quos omnis. Et quas inventore quas aut ut. Doloribus earum voluptas repellat ut. Numquam eaque ut consequatur.</p><p>Quia deserunt dolor sit esse quasi vel fuga. Consequatur quibusdam esse rerum quam qui doloribus qui dolores. Adipisci inventore ad aspernatur nemo. Aut quos accusantium nihil repudiandae qui laudantium.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05');
INSERT INTO `posts` (`id`, `category_id`, `user_id`, `title`, `slug`, `image`, `excerpt`, `body`, `published_at`, `created_at`, `updated_at`) VALUES
(32, 4, 2, 'Animi corporis expedita magnam occaecati quidem exercitationem dolores est inventore at.', 'doloremque-doloribus-nam-sit-quis-dolores-dolor', NULL, 'Dolorem sint et deserunt iusto harum ut animi ipsam possimus corrupti quia quibusdam aut inventore ut corrupti.', '<p>Voluptatem temporibus doloremque eos. Nobis beatae ex ea cupiditate odit. Dolore tenetur qui voluptatem quia architecto provident quidem illo. Qui distinctio exercitationem asperiores voluptatem.</p><p>Consequatur hic mollitia debitis saepe omnis aut eum. Id ut provident esse et ut totam. Exercitationem numquam fuga quae numquam quia. Dolore quasi fuga consectetur esse animi omnis id facilis.</p><p>Dignissimos doloribus consequatur quasi corporis excepturi et. Unde voluptatum qui nemo consequuntur incidunt.</p><p>Vel reiciendis libero quia deleniti consequatur quod. Dolorem eum ut rem quas. Numquam repellendus in harum sit delectus.</p><p>Ut earum quo omnis voluptatem omnis quae neque eum. Ipsum sunt voluptatem odit cum molestias numquam. Atque vel rerum enim voluptatem officiis tempore qui porro.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(33, 3, 3, 'Minima dolores enim odio nam nostrum velit ut velit reiciendis consequatur inventore nesciunt.', 'voluptatem-minima-magnam-possimus-id-assumenda', NULL, 'Eos quia aliquam libero cupiditate quis nisi cumque voluptatem maiores est aut in dolore animi iusto doloribus odio laboriosam ducimus.', '<p>Sunt minima quae sed odio. Explicabo eos sint laudantium rem officia earum. Veniam et omnis assumenda ut.</p><p>Consequatur maiores dicta sed veritatis quod veniam. Dolores sapiente maxime id temporibus. Omnis tenetur nesciunt ipsam ab voluptatem odit.</p><p>Doloribus voluptate doloremque odio facere numquam ea. Cum nostrum quasi nihil asperiores.</p><p>Dolores et optio et reprehenderit modi iste doloremque. Dolorem qui dignissimos fugiat eius nisi unde suscipit sit. Cum suscipit optio veritatis possimus nihil. Aut qui ea dolorem soluta.</p><p>Cumque voluptatem optio et animi. Perferendis facilis consequatur occaecati. Velit ut exercitationem eius architecto quos. In earum blanditiis est laudantium perspiciatis eligendi.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(34, 4, 2, 'Non illum fugit suscipit tempora veniam ut eos reprehenderit.', 'tenetur-voluptates-quaerat-ea-ipsum', NULL, 'Placeat cumque laborum optio numquam vel in ex excepturi dolorum consequuntur est veritatis incidunt a qui aut est quia natus ut dignissimos ut dignissimos quis ut molestiae consequuntur culpa voluptas quibusdam quaerat nisi.', '<p>Delectus sed repudiandae aliquam rem mollitia et fugit. Quod vitae distinctio quia in quidem voluptatum. Aut dolor fuga aperiam officia dolore eius doloremque nesciunt.</p><p>Doloribus non quos cumque consequatur tempora. Nihil aut voluptates id. Voluptatem rerum amet et mollitia debitis. Est quae voluptatem esse autem.</p><p>Dolorum a et quam eos rerum est. Officiis vitae maxime aspernatur sed nemo. Eos aut commodi expedita aut ut recusandae.</p><p>Enim et ea quo in. Nisi dolorum officiis consequatur necessitatibus sit magnam maxime.</p><p>Et doloribus id sit ab eveniet quos. Et necessitatibus ut et animi eum fugit est. Iste error voluptates natus enim sint.</p><p>Porro nobis voluptatum exercitationem debitis tempore repellendus odit. Laboriosam animi rem quam quod id minus qui. Enim ut cum omnis iusto iste. Vitae hic natus dolor quae ducimus aut. Odit aut aperiam veniam doloribus voluptates est beatae.</p><p>Omnis repudiandae ullam deserunt sed voluptatem est. Accusamus dolorem corporis consequatur. Sequi et sint earum quibusdam totam sit quidem omnis. Aperiam dolor et est id eveniet ut.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(35, 3, 1, 'Sit ratione sequi vel suscipit.', 'ut-et-nesciunt-dolores-omnis-adipisci', NULL, 'Nesciunt itaque iste aut facere vero rerum qui dolorem accusantium odio vero dolores aut aliquam voluptas.', '<p>Vel neque velit laborum aut excepturi. Alias veniam doloremque ut molestiae dolor. Velit enim ea officia ex esse dolor repellat.</p><p>Illo facilis harum dolorem quidem doloremque harum sint veritatis. Doloremque et et molestiae nihil eaque ut. Omnis nihil iure perspiciatis consequuntur alias fuga inventore aut. Est tempore suscipit ipsum consectetur laborum adipisci.</p><p>Fugiat qui necessitatibus non quo tenetur. Corrupti et eaque vitae ipsam. Culpa ex cupiditate a aut veritatis molestias.</p><p>Voluptatem quos debitis voluptatem ut deleniti eaque. Rerum quod et consequuntur quaerat sint omnis. Voluptatem iste voluptatem aut sit qui quidem. Esse nesciunt consectetur maiores ea voluptates.</p><p>Et ut corrupti quidem. Expedita ipsa voluptas ipsum molestias est ullam. Eius dolores sunt alias reiciendis animi.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(36, 1, 3, 'Soluta omnis qui aut cum.', 'quas-nesciunt-sunt-aperiam-aperiam', NULL, 'Sint ipsam natus qui tempora molestiae minus qui tempore aspernatur doloribus ad repellendus facilis tenetur nam iusto earum aliquid voluptatem possimus dolorem repudiandae accusantium blanditiis delectus.', '<p>Eius voluptatem voluptatum expedita deserunt. Iusto eveniet ab vel accusamus nobis.</p><p>Ut aut et suscipit aliquam. Velit vitae dolores dolorem et aliquid incidunt quisquam. Blanditiis culpa ut a reprehenderit est velit.</p><p>Eligendi eaque dolores alias rerum exercitationem quia. Voluptatibus velit eum dolores ullam vero sed. Est voluptates doloribus sed.</p><p>Velit saepe maiores voluptatem et rerum. Qui ut tenetur vel minima doloribus magni et voluptatem. Cupiditate totam reiciendis magnam nisi soluta nemo qui. Voluptas repudiandae quia voluptas ea et nihil sit nisi.</p><p>Provident voluptatem facilis id optio soluta. Accusamus voluptatem et provident minus quis quia. Suscipit vel mollitia facere iste expedita architecto. Aliquid sit quia deleniti quos labore et perspiciatis.</p><p>Et error sed repellendus maiores est eveniet. Sed laudantium aliquam eaque sint facere est culpa. Laboriosam ipsa corporis labore quia vel porro est.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(37, 4, 2, 'Laboriosam placeat facilis aut.', 'cumque-illo-porro-laborum-est-natus-perspiciatis-ad', NULL, 'Eaque ut dolorum reiciendis maiores ut animi recusandae cum sed culpa ea quod eos placeat.', '<p>Error et saepe debitis harum rerum. Soluta et accusamus delectus nulla atque.</p><p>Odit quia et quisquam est et. Et autem repudiandae a autem sed sed eaque. Enim molestiae provident sequi recusandae qui nobis debitis.</p><p>Sit facere autem impedit quo natus adipisci. Odio unde quod assumenda. Repudiandae ipsam consequatur facilis et expedita rerum illum.</p><p>Nisi ipsam aut unde dolor saepe culpa porro. Provident accusamus aut consequatur. Et et exercitationem maiores. Voluptates blanditiis recusandae in dolores.</p><p>Et et qui temporibus fugit quis consectetur. Repellendus quis quisquam quia praesentium dicta. Ea nam corporis et officiis omnis aut a. Iusto quidem eos consequuntur odit sed repudiandae modi.</p><p>Aliquam harum consequatur id temporibus cum est dolorem ut. Sit voluptatum voluptate eveniet quos.</p><p>Asperiores quae deserunt sint numquam unde. Molestiae quis dolores et rerum fugiat quia sunt. Qui maxime magni cumque corporis id.</p><p>Soluta perspiciatis laboriosam sed expedita velit sit. Consequatur dolorem qui et enim id veniam recusandae. Sed consequatur nemo sequi voluptatum eveniet libero. Quas nesciunt voluptates quia nam repellendus impedit vel.</p><p>Beatae suscipit quos enim cupiditate maxime quod. Neque nihil eligendi aut facilis voluptatem. Itaque quibusdam sunt occaecati deleniti.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(38, 1, 1, 'Voluptatum facere sapiente laudantium explicabo tenetur et sequi.', 'voluptatem-earum-eligendi-numquam', NULL, 'Et in architecto iure qui alias ad provident ipsum aut quis soluta laborum voluptatem et qui et dolores hic autem est dolor necessitatibus est et ullam.', '<p>Voluptatibus dolorem velit ad odit quo. Rerum aut rerum repudiandae ab nisi quia architecto. Pariatur quo sed qui et hic suscipit nostrum.</p><p>Vero non ea eius commodi cumque alias voluptatem. Cumque consectetur quisquam ea. Sit veritatis rerum alias numquam.</p><p>Dolorem quia vel nemo adipisci in. Hic ipsam rerum laudantium dolore at quia. Ut vel perferendis et sit. Rerum debitis vel maxime libero vero nisi.</p><p>At eos cupiditate et nostrum. Eum repudiandae aspernatur quis ratione voluptatem. Reiciendis voluptates harum ea incidunt nihil maiores nostrum ipsa. Corrupti numquam iusto tempora quo voluptatibus. Accusantium enim vero consequatur quisquam dolore.</p><p>Ut nam dolorem doloremque quisquam ut quasi qui. Maxime temporibus cum laudantium est cum. Dolor at eligendi quis illo molestiae. Qui illo eius est.</p><p>Doloremque sit eum provident vero minus atque. Architecto nihil saepe laborum. Ut quas aperiam deserunt. Eligendi dolor suscipit facere animi inventore eius.</p><p>Cumque assumenda iusto non blanditiis nostrum enim possimus. Tenetur cumque cupiditate officiis dolores accusamus. Ex cumque tenetur fugit consectetur delectus.</p><p>Suscipit perspiciatis earum ut consequatur sint natus. Earum quam quia dolore est. Sunt excepturi quia consequatur.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(39, 3, 2, 'Fugit sequi qui et et repudiandae culpa recusandae quisquam.', 'omnis-et-dicta-mollitia-et-et-cumque', NULL, 'Temporibus excepturi possimus commodi doloribus optio perferendis fugiat quia dolorem corrupti aut culpa dignissimos doloribus consequuntur et impedit nesciunt velit dolores at aut dolorum et natus non et id rem.', '<p>Maxime modi laudantium et tempora. Voluptatem libero a facilis et. Error possimus ea sequi optio voluptatem. Et voluptas distinctio laboriosam voluptatem praesentium quia totam. Recusandae et sed quia modi maiores ratione dignissimos vitae.</p><p>Velit autem aliquid dolorem molestias sit. Doloribus praesentium nobis recusandae ut voluptatum. Qui facilis fuga perspiciatis id et deserunt at. Temporibus reprehenderit perspiciatis nesciunt voluptatem itaque.</p><p>Sint sunt corporis quod dicta. Praesentium laborum exercitationem qui beatae non dolorum sapiente exercitationem. Qui quia neque suscipit cumque et unde.</p><p>Sit quibusdam et sunt accusantium tempore. Provident et nobis exercitationem modi impedit. Enim est nostrum a alias dolore maiores.</p><p>Deleniti nisi et consectetur dolores. Sed aut cumque sint asperiores. Vitae non est cum dolores autem sapiente.</p><p>Excepturi eos soluta rerum autem qui consequatur nemo. Molestiae laboriosam consequatur quisquam. Enim similique nulla atque omnis.</p><p>Aliquam excepturi dolores voluptate impedit eos ad consequatur corporis. Distinctio cumque illo et. Veritatis autem nam omnis ullam aut cumque autem. Aut eos sunt ipsa nostrum voluptatem exercitationem.</p><p>Quia iure id aut praesentium fugit. Nam eaque error commodi ad. Eos fugit officia consectetur deserunt. Fugiat non quia neque aut doloremque. Accusantium consectetur et quis aliquam expedita.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(40, 1, 3, 'Qui et qui eligendi.', 'error-qui-totam-voluptatem-excepturi-qui', NULL, 'Dolores atque beatae qui provident consequatur aperiam nesciunt labore ea et quam porro sit vel porro et ut enim et eius molestiae atque consequatur aut suscipit necessitatibus sint.', '<p>Ut ut dolorem et dolorum. Ipsam qui ea aut quaerat. Omnis enim et asperiores pariatur sit.</p><p>In ea veniam nesciunt est veniam id aut et. Et et officia ut repudiandae quod. Sunt accusamus aut eos ab dignissimos a perspiciatis. Cum ad dolor id distinctio iusto. Veritatis totam et repudiandae suscipit suscipit sit ducimus.</p><p>Sint sed et neque quo. Explicabo adipisci dolor eos ea ratione saepe nisi a. Molestiae voluptas quia repellendus optio perferendis sapiente.</p><p>Qui voluptatem tempora consectetur iure quia illum tempora voluptas. Sed sed ex qui deleniti rerum voluptatem atque. In voluptas autem sequi quia saepe. Itaque nihil consequatur et modi non itaque.</p><p>Non velit quis ut et placeat necessitatibus. Aperiam exercitationem maxime recusandae nam accusantium corporis. Nihil sapiente mollitia ut sapiente. Quae voluptas non mollitia officiis quia et cumque.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(41, 5, 2, 'Ea dolorem odio placeat.', 'error-delectus-consequatur-sit-natus-culpa', NULL, 'Laborum non doloribus vel veniam provident tenetur aspernatur deserunt molestiae ab dolorem repudiandae et molestiae sit rerum accusamus pariatur illo ut eius officiis repudiandae neque labore id nulla.', '<p>Accusantium qui minus explicabo. Quia ipsa modi dolor eum.</p><p>Consequatur ut ad enim odit voluptates. A accusamus optio consequatur rerum. Cupiditate facilis quia voluptatem fugiat.</p><p>Iste laboriosam dolore quam molestiae. Doloribus ab facilis ut eum facilis atque aut distinctio.</p><p>In repellat maxime culpa quod est. Rerum temporibus minima voluptatem voluptates sit omnis. Qui rerum vitae consequatur est quia.</p><p>Nesciunt nulla quibusdam dolores quia. Vitae dolore consequuntur non error eum recusandae itaque. Ut eveniet reiciendis quia vel eum iure. Vero ex quo et non.</p><p>Quis totam nihil velit sapiente sed. Illum labore inventore iste nulla. Sit voluptatem animi atque doloremque velit.</p><p>Eos voluptatem commodi tempora occaecati accusamus velit consequatur. Modi ratione aut architecto tenetur nulla voluptatem repellat aut. Autem repellendus repudiandae quis aut aut. Rerum repellat saepe eius omnis nisi.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(42, 4, 3, 'Quo ipsum consequuntur molestiae culpa est et facere est assumenda.', 'et-aut-impedit-similique', NULL, 'Tenetur voluptatem quis qui nam ipsum impedit dicta rerum distinctio omnis ea aliquid sit aperiam et enim.', '<p>Molestias aut sint magnam libero nostrum cupiditate. Earum iste enim quia ut. Dolores omnis sunt qui explicabo vel.</p><p>Eum suscipit voluptatum consequatur voluptatem. Atque dolore nam illo aut. Aut quo ut placeat delectus.</p><p>Dolorem et sit aperiam pariatur officiis est delectus. At corporis dolorem quos in ipsam. Voluptas maiores debitis tempore mollitia. A consequuntur veniam accusantium ut accusamus. Accusantium minus enim sed et cupiditate.</p><p>Facere nisi modi cumque impedit alias unde sint. Laboriosam fugit magni fugiat qui velit aut. Velit labore quia quo eum reprehenderit cupiditate. Quod qui modi pariatur labore voluptates sed doloribus.</p><p>Placeat quae qui modi repudiandae est. Omnis explicabo officiis non accusamus eos. Rerum esse veniam molestias nemo eum ab. Pariatur reprehenderit est minima ea nam et voluptatem. Consequatur distinctio vitae qui laudantium ut nihil.</p><p>Perferendis voluptate ad dolore eos. Temporibus repellendus voluptate quis. Autem dolores culpa a maxime impedit aspernatur possimus beatae.</p><p>Exercitationem ut nostrum laudantium nesciunt. Aut corrupti aut molestiae rerum eaque. Dolores aperiam quod quibusdam dolor. Et possimus eos earum eos.</p><p>Assumenda voluptatum itaque deserunt eveniet neque quaerat. Aliquid optio doloremque ducimus sit rerum laudantium. Provident distinctio alias illo voluptates aut. Quas rerum ducimus quibusdam consequatur iusto. Magni qui ex nobis magnam dignissimos esse.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(43, 5, 2, 'Eaque aperiam repudiandae mollitia est amet rerum quisquam cum et omnis debitis eaque quisquam magnam.', 'officiis-corrupti-illum-vitae-sequi-non-quaerat', NULL, 'Sequi vero ullam nobis et voluptatem necessitatibus aut qui eos impedit ut quos at sunt laborum illo.', '<p>Nobis recusandae quasi ullam autem explicabo. Cumque iure est quam delectus voluptates adipisci error. Enim mollitia eaque aut ducimus.</p><p>Nostrum a odit voluptatem ea est sed. Ex similique magnam ducimus voluptatem repudiandae maxime exercitationem. Enim sed minima dolorum libero velit. Id cumque voluptatem nemo rerum. Aut illum voluptas facere accusantium.</p><p>Autem sed rerum omnis voluptas fugit ea ea recusandae. Impedit et esse doloremque autem adipisci fuga. Debitis quidem possimus et atque. Reprehenderit facilis saepe necessitatibus maiores quo. Culpa fugiat neque unde repudiandae et assumenda repellat.</p><p>Quia aut quam vero velit voluptatem blanditiis eveniet. In reiciendis qui aperiam sequi dolores itaque. Ut aut vel voluptas aut magni iure et.</p><p>Fugit iure qui aliquid fugit eveniet qui. Distinctio ut et similique voluptatem eum. Excepturi qui vel at eum modi.</p><p>A similique quia numquam voluptatum. Doloremque aperiam ea consectetur quaerat quas asperiores. Assumenda et quia nisi ea. Non nihil consequatur quidem et.</p><p>Quis ratione atque suscipit enim sit omnis optio. Minima quo amet praesentium et omnis. Deleniti suscipit qui dignissimos sed distinctio omnis aut. Et quaerat esse ad necessitatibus error accusamus. Recusandae error ratione voluptas perspiciatis et alias.</p><p>Exercitationem et nobis porro ullam excepturi. Amet ipsam voluptatum deleniti est et qui nesciunt. Quo odit officiis vero et eaque. Error molestiae voluptates consequatur et aspernatur voluptatum quia.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(44, 2, 1, 'Sapiente praesentium quia eos est facilis.', 'nulla-recusandae-commodi-labore', NULL, 'Aperiam nisi sunt deleniti distinctio consequatur molestias quam at provident ea perferendis et sit vel perferendis minus et veniam.', '<p>Quisquam qui officia perferendis doloribus. Error facilis vel perferendis possimus et deleniti. Et ut sint ea aliquid. Qui dolores laborum quod recusandae in in.</p><p>Minus voluptas eveniet voluptates nostrum earum. Aspernatur laborum in aut ut voluptatibus. Voluptates aut architecto natus ut praesentium.</p><p>Vel maxime beatae nobis in saepe ducimus non. Ab qui laboriosam in quibusdam odit sit aliquid beatae.</p><p>Aut sequi iste dolor ut quo numquam. Et autem inventore nemo eius quaerat vero praesentium. Exercitationem culpa consequatur nihil voluptatem. Velit qui et aperiam pariatur et deleniti atque ut.</p><p>Veniam nesciunt a cumque qui sed reiciendis. Deserunt laborum iste facere est dolorem omnis et.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(45, 1, 3, 'Eos animi earum accusamus eveniet ullam et eveniet.', 'consequuntur-nihil-consequatur-ipsa-quia-sunt', NULL, 'Repellat et vel rerum voluptatem reiciendis suscipit qui optio earum excepturi molestiae aut mollitia non et commodi voluptatibus ut et et quaerat aut provident rerum dolorem qui dolorem.', '<p>In neque recusandae asperiores veritatis. Quis est qui sed inventore vitae. Qui vel non architecto totam molestiae ut. Necessitatibus aliquam ut qui consequatur quas enim.</p><p>Distinctio rerum tempora repellendus totam odit quibusdam. Inventore qui autem voluptas voluptatum distinctio. Voluptatem repellat harum harum laborum voluptatem quam mollitia. Modi in non nostrum ut et laboriosam unde. Rem corporis laboriosam doloribus sit quae.</p><p>Nostrum et laborum quisquam magni rerum cupiditate voluptas. Fugiat hic natus et aut ipsum rerum. Laborum harum et eligendi. Numquam sit ducimus quia sint doloribus eum facere.</p><p>Aut at optio in magnam vel veritatis. Itaque eaque enim aliquam assumenda vel nihil reiciendis. Molestiae nihil autem excepturi rerum.</p><p>Ducimus in nobis et quia consectetur. Vero est possimus illum velit soluta earum reiciendis. Dolorem eius sit totam vel esse repellat.</p><p>Vero nam consequatur qui expedita ut qui cumque. Veritatis mollitia dolore officiis. Ea in iste laudantium aliquid mollitia.</p><p>Ut dolores praesentium consequuntur laudantium ut. Qui eaque ut consectetur. Aut dolores ex iste voluptatem numquam id.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(46, 3, 1, 'In dolores voluptate sunt aliquid iure dignissimos est officiis porro.', 'explicabo-assumenda-nesciunt-aut-in-officiis-doloribus', NULL, 'Ea minus assumenda ex dignissimos nobis voluptate sed corporis cum id quod sunt et praesentium minima quos doloremque esse velit mollitia voluptatum cumque ducimus enim quia quia praesentium dolor.', '<p>Eum id qui vitae eum. Quibusdam ut dolor et aliquid debitis. Repellendus minima nostrum officiis vero ut. Non natus eum labore qui.</p><p>Fugiat quos maxime dolorem vel fuga pariatur quibusdam et. Qui nulla dolorem ut est. Fuga aut cum repudiandae. Voluptatem aut et quis animi et nihil ad praesentium.</p><p>Consequatur cumque natus natus dolor vel voluptatem. Repellat voluptatem consequatur corrupti debitis et. Aut optio assumenda voluptas iste tempora consequatur. Et expedita cupiditate voluptatem.</p><p>Voluptatem corporis ipsam laudantium amet atque ipsam praesentium. Iste ut neque distinctio modi rerum natus nostrum. Iure consectetur voluptatem et alias cupiditate.</p><p>Est dignissimos saepe aut accusantium. Nisi cum veniam officia voluptatem suscipit qui veritatis. Odio sint in modi soluta dolor. Velit nemo ut id suscipit illo voluptatem.</p><p>Nulla non iusto recusandae in odio neque veniam. Suscipit molestiae soluta quia molestiae. Excepturi delectus perspiciatis aspernatur at quaerat architecto.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(47, 1, 2, 'Voluptatem dicta laudantium voluptatem ex incidunt.', 'magnam-quia-dolorem-labore-doloribus-voluptas', NULL, 'Veniam quaerat qui qui in et illum voluptate quas nihil eum enim quasi aut ea modi enim aut omnis ad ullam accusamus soluta laboriosam maxime omnis quisquam alias qui.', '<p>Rerum molestiae et nobis ut velit ullam. Et vel dolorem reiciendis rem recusandae sed. Non eum aperiam ut voluptates impedit occaecati. Vitae pariatur iste ea dolor ea.</p><p>Totam et facilis ea recusandae. Asperiores exercitationem voluptas qui sunt. Nisi eum quae aut vero ea consequuntur. Reiciendis perferendis natus quia ullam aut.</p><p>Et ut possimus voluptatem assumenda dicta cupiditate laudantium. Rem soluta repellendus excepturi vel minima quas. Aut veniam dignissimos facilis necessitatibus aut. Rerum nesciunt commodi necessitatibus nobis. Id labore totam ipsum optio vel molestias.</p><p>Officiis eaque amet porro dignissimos pariatur quasi nulla. Deleniti autem provident debitis. Expedita consequatur architecto laboriosam ad nesciunt voluptate. Nihil libero architecto velit.</p><p>Nihil magni eos repudiandae quis deserunt iure earum. Atque rerum quaerat sed qui veniam non. Qui excepturi alias aut mollitia consectetur.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(48, 2, 2, 'Illo saepe nulla reprehenderit animi.', 'ullam-vel-enim-deserunt-corrupti', NULL, 'Facere et eaque et quibusdam qui quisquam qui rerum quam consectetur consectetur porro error odio minima quia ab et est ut voluptatibus voluptatem qui.', '<p>Quia voluptatum et eaque reprehenderit. Et est atque eius animi ea velit minus vel. Placeat ut repellat non tempore illo autem consectetur. Et quod doloribus in cumque debitis fugiat atque perspiciatis.</p><p>Et accusamus amet rem laborum. At corrupti necessitatibus dolorem et fugiat. Omnis rerum error labore sequi quisquam inventore.</p><p>Quia quam unde magni cum est laudantium ea. Ad dolor odio eius porro. Voluptates animi voluptas ratione eligendi omnis. Quisquam aut assumenda nisi totam veniam fugit dicta.</p><p>Perspiciatis illum quo asperiores modi rerum. Perspiciatis doloribus at aspernatur id voluptatem iusto sint. Totam quod fugiat totam neque dolor. Rem aut sit dolor odit.</p><p>Dolore tempora unde ipsum nulla ratione. Harum ut necessitatibus unde temporibus commodi. Iste non saepe recusandae deleniti.</p><p>Id impedit dolorem rem eveniet voluptatem atque dolore quaerat. Quia et nobis sit ipsa nemo. Cum in impedit culpa totam non recusandae sint. Quia aut maiores voluptatum occaecati et dicta aliquid tempora.</p><p>Quia quaerat tempore et cum beatae temporibus voluptas numquam. Saepe temporibus ratione omnis saepe. Odio voluptatibus ut consequuntur modi accusantium non. Et autem accusantium molestiae ut rerum aut est. Saepe dignissimos possimus rem aliquid consequatur inventore.</p><p>Esse laudantium nostrum voluptatem nam blanditiis. Consequatur consequatur nihil vero. Facilis nam quidem aliquam. Consequatur molestias rerum veritatis ea. Sit officia quis dolores ut.</p><p>Voluptas quo magni nostrum at. Sed dignissimos veniam qui sit sit consequatur. Voluptas minus eum qui iusto adipisci. Nobis aut accusantium sit sed.</p><p>Eos vel maxime veniam sit nihil. Eum fugit aliquid reiciendis commodi officiis sed esse. Eos illo beatae maiores architecto eaque praesentium. Debitis quo labore rerum voluptatem dolor facere eligendi.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(49, 3, 2, 'Eum quod qui et consequatur unde ea aliquam eos in.', 'nostrum-nam-maxime-nobis-ullam-quis-voluptate-quae-vel', NULL, 'Atque optio vitae sed placeat a quod aliquam deleniti eos tempore consequatur accusantium ut ea delectus eligendi et aut nostrum possimus.', '<p>Non quia autem ea. Voluptates amet adipisci magni. Ullam amet accusantium earum laudantium qui officia.</p><p>Qui harum dolor modi. Aut et nostrum nemo quidem sed tempora quia velit. Aut repudiandae odit earum rem. Impedit excepturi maxime fugiat beatae.</p><p>Odit qui voluptatem quis ipsum. In autem quaerat ut est nesciunt reiciendis tenetur. Quia doloribus quam repellendus ullam maxime repellendus.</p><p>Molestiae est consequuntur maiores delectus possimus. Sunt eius aliquam maxime id iste sit. Aut cum soluta quo nam nemo.</p><p>Consequatur reprehenderit nostrum molestiae reprehenderit et et eos. Consequatur dolore incidunt inventore harum omnis est. Distinctio repellendus sapiente doloribus ut atque ut. Sapiente voluptas sit et harum voluptatibus dolor dolores.</p><p>Dolore neque nemo dignissimos est earum est et. Vero consequuntur non tempora voluptas. Aut nobis aut nesciunt.</p><p>Eveniet voluptas nulla impedit. Enim velit dolorem animi est a natus. Ut optio sed quaerat dolores alias et velit.</p><p>Omnis qui dolores assumenda dolore non praesentium enim. Dolor consequuntur similique ut dicta facilis laudantium. Officiis dolores harum consequatur velit ut.</p><p>Dolores soluta dolor dolores quas dolorem quia. Rerum et cumque impedit nulla cumque sequi incidunt. Eum laudantium fugit placeat. Voluptatem eum ullam mollitia in dolor reiciendis.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05'),
(50, 3, 3, 'Id omnis non dicta optio qui error aut rerum quasi nesciunt dolorem neque.', 'tempore-nemo-et-deleniti-iure-explicabo-sit-aut-dolores', NULL, 'Dolorem doloribus incidunt nulla cupiditate ab quo eveniet corrupti omnis ut natus sit quod eligendi dolores et tempora id architecto et autem repudiandae ipsum debitis in commodi.', '<p>Et explicabo vel magnam voluptatem at aperiam. Ut qui ipsa sit soluta. Dolor praesentium sint sunt est numquam. Eaque quidem natus aut rerum. Maiores ut eveniet itaque deserunt deleniti reiciendis.</p><p>Exercitationem voluptas expedita magnam aut molestiae. Labore qui velit omnis quam omnis porro enim eligendi. Sit eius animi eos nam vero.</p><p>Rerum officiis adipisci nisi. Aut repudiandae distinctio quasi soluta amet autem dolores. Voluptatem in ut consequuntur. Eos consequatur aut qui.</p><p>Omnis illo ducimus temporibus illo labore sed quas. Quas consectetur aut assumenda quos eaque ea. In maxime vel ipsam et reprehenderit.</p><p>Atque ut natus sed repudiandae praesentium aut fugit. Et sunt quia dolorum et et. Fuga et nemo atque dolores illo repellendus voluptatem. Dolores nemo pariatur velit aperiam est.</p><p>Maiores molestiae ea ipsum voluptatem voluptatibus et. Quia quis eum eos quia. Accusamus architecto vel dicta similique est. Voluptatem consequatur ipsa natus ea.</p><p>Sit architecto expedita adipisci rerum tempora. Eius ad saepe inventore dolorem aut. Odio quaerat at dicta tempore qui. Autem eum tempore ea ad quibusdam.</p><p>Impedit porro exercitationem perspiciatis. Vel ut ea consequatur. Ad eos cumque doloremque ut.</p>', NULL, '2023-09-04 22:56:05', '2023-09-04 22:56:05');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `username`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `is_admin`) VALUES
(1, 'Baktiono Hidayat', 'baktionohdyt', 'baktionohdyt@gmail.com', '2023-09-04 22:56:05', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'd1zLfjuQKxck6fxG9vwuPKwKQzhDDubwSkAi9xzRlRZwV2Or8umBFkDlXF7G', '2023-09-04 22:56:05', '2023-09-04 22:56:05', 1),
(2, 'Tami Amelia Widiastuti S.Psi', 'tamiamelwidi', 'tamiamelwidi@gmail.com', '2023-09-04 22:56:05', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'A08ttMjBUb1xQTWq5JwRZSf4KGmMNmnUtNfhBj6uSj29CPn9s2YeXnnVtTVl', '2023-09-04 22:56:05', '2023-09-04 22:56:05', 0),
(3, 'Oliva Yolanda', 'olivayolanda', 'olivayolanda@gmail.com', '2023-09-04 22:56:05', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'RNYmeQUYcrPjbLcRHoOzRZXO7IAMj7fBEohZ9GFKnoUeyzj5fr6wPehfi1aB', '2023-09-04 22:56:05', '2023-09-04 22:56:05', 0),
(4, 'Amalia Citra Lestari M.Pd', 'amaliacitralestari', 'amaliacitralestari@gmail.com', '2023-09-04 22:56:05', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'xT2G0Q1j5seDWVraw89bMdyjRnfdHa4rA4qQ3hiKsfL6on1hQ0VL0kYJ7Wbz', '2023-09-04 22:56:05', '2023-09-04 22:56:05', 1),
(5, 'Eko Marbun', 'ekomarbun', 'ekomarbun@gmail.com', '2023-09-04 22:56:05', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'LUJQPeqfJE', '2023-09-04 22:56:05', '2023-09-04 22:56:05', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `categories_name_unique` (`name`),
  ADD UNIQUE KEY `categories_slug_unique` (`slug`);

--
-- Indexes for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`);

--
-- Indexes for table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `password_resets`
--
ALTER TABLE `password_resets`
  ADD KEY `password_resets_email_index` (`email`);

--
-- Indexes for table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  ADD KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`);

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `posts_slug_unique` (`slug`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_username_unique` (`username`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
